### ISSUE TITLE
La barre de chargement des fichiers intégré dans la page : super bien !!!!

### ISSUE THREAD

**Issue by AntoineRault** [vincenthure/postmedias-beta#14]
La barre de chargement des fichiers intégré dans la page : super bien !!!!
ce qui serait hyper classe et jamais vu et je sais pas si c'est possible : pouvoir passer à l'étape suivante tout en ayant la barre de chargement du fichier qui évolu en haut, ce serait hyper pratique, le client pourrait rentrer ses infos pendant que ses fichiers charges !!!

**Comment by AntoineRault** [comment]
peut etre une petite croix à coté de la barre de chargement au cas ou le client s'est trompé de fichier et voudrait annuler l'envois.

**Comment by vincenthure** [comment]
C'est une fonction qui serai effectivement interessante
Elle nécessite de repenser complètement le chemin de la commande.
J'envisage de trouver une solution comme cela : 
charger toutes les etapes 1 à 6 dans une même page
installer les six etapes dans six onglets
installer deux boutons en bas de page pour aller d'un onglet à l'autre
c'est un gros chantier

**Comment by vincenthure** [comment]
Pour le bouton annuler je suis d'accord
je ne sais pas encore comment le faire, il faut que je regarde ça.
les fonction d'upload vienne d'un module que j'ai récuperé et il n'intégre pas de base cette fonction.

**Comment by vincenthure** [comment]
Après des essais j'abandonne l'idée de mettre toutes les etapes de la commande dans une seule page et multiples onglets. Ca remets trop de chose en cause pour être réalisable. 
Par contre j'ai changé l'ordre des étapes, ainsi les gens peuvent voir l'estimation du devis avant de commencer l'upload

**Comment by vincenthure** [comment]
done
