### ISSUE TITLE
 ne pas proposer le calendrier lorsque le client a décoché "voix off" au début

### ISSUE THREAD

**Issue by AntoineRault** [vincenthure/postmedias-beta#15]
ne pas proposer le calendrier lorsque le client a décoché "voix off" au début

**Comment by vincenthure** [comment]
cette fonction a déjà été installer
j'ai fais un nouvel essai et chez moi et ça marche
peux refaire un essai?
me donner des infos sup sur ce que tu as fais.

**Comment by vincenthure** [comment]
done
