### ISSUE TITLE
la date de création est toujours en anglais, la mettre en français

### ISSUE THREAD

**Issue by AntoineRault** [vincenthure/postmedias-beta#16]
la date de création est toujours en anglais, la mettre en français

**Comment by vincenthure** [comment]
merci c'est super 
je regarde tout ça ce week-end 
vincent 

Envoyé de mon iPhone

**Comment by vincenthure** [comment]
il est possible d'internationaliser l'affichage des dates.
J'ai déjà fais des essais dans ce sens mais pour l'instant je rencontre des difficulté pour installer et utiliser ce module.

**Comment by vincenthure** [comment]
DONE
