### ISSUE TITLE
Calcul de devis - Prioritaire

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#20]
Aucune infos pour l'utilisateur pour définir cette notion de prioritaire
parcours souhaitable :

1. Demande du delais souhaité pour le mixage (à partir de l'acceptation du devis)
2. Si délai > à notre notion de prioritaire on lui propose de faire + vite (genre Amazon Premium)
3. Si délai > à notre notion de prioritaire on lui donne le coût  supplémentaire
![click mix - devis](https://user-images.githubusercontent.com/29533634/27302726-8cd0158a-5538-11e7-815a-c3f343d1432e.png)

**Comment by vincenthure** [comment]
Done
