### ISSUE TITLE
Mise aux normes - Optimisation de la landing page

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#23]
- Clarifié la page
- Moins de texte
- Visuel non adapté
- Revoir le parcours 
 Envoi du fichier / Demande l'Email pour envoi du résultat
![click mix - public_robot_lufs](https://user-images.githubusercontent.com/29533634/27303006-8752b2ce-5539-11e7-999e-82d871f6353a.png)

**Comment by vincenthure** [comment]
Done sauf le visuel
