### ISSUE TITLE
Mise aux normes - Message de traitement du fichier

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#24]
Call to action :
- Partager le service : Facebook, linkedin
- Découvrir le calcul de devis
- tous les avantages C&M
![fireshot capture 289 - click mix_ - robot_pending](https://user-images.githubusercontent.com/29533634/27303239-722f40f0-553a-11e7-8691-0e830605dcb9.png)

**Comment by vincenthure** [comment]
done
