### ISSUE TITLE
Créer votre compte - Confirmation création de compte

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#27]
Changer Call to action : "Retour à la page d'origine" par "Bravo ! Nous pouvons commencer votre 1er projet Click & Mix" ou un truc du genre
![click mix - register_confirmed](https://user-images.githubusercontent.com/29533634/27304051-221d746c-553d-11e7-8f30-6e78ca06a0f0.png)

**Comment by vincenthure** [comment]
Done
