### ISSUE TITLE
Nouveau Projet Etape 1/5

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#28]
Cochez si besoin de voix off
Emplacement, design et wording du bouton continuer à revoir : (Suivant, Etape 2, ...)
![click mix - client_nouveau-projet-etape1](https://user-images.githubusercontent.com/29533634/27304224-ae31ebc2-553d-11e7-93a3-faba66ba9765.png)

**Comment by vincenthure** [comment]
done
