### ISSUE TITLE
Nouveau Projet Etape 1/5 - Abandonner la commande

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#30]
Remplacer par RETOUR ESPACE CLIENT (par ex)
Message : Attention votre projet n'est pas encore finalisé vous risquer de perdre vos informations ... (à définir)
![click mix - client_nouveau-projet-etape1](https://user-images.githubusercontent.com/29533634/27304427-52c0762c-553e-11e7-86d5-e277d8b71179.png)

**Comment by vincenthure** [comment]
done
