### ISSUE TITLE
Nouveau Projet Etape 1/5 > 3/5

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#31]
Si pas de voix off l'utilisateur passe de l'étape 1 à l'étape 3
![click mix - client_nouveau-projet-etape1](https://user-images.githubusercontent.com/29533634/27304630-f84f13e6-553e-11e7-88c1-bda2c88701a0.png)
![click mix - client_nouveau-projet-etape3](https://user-images.githubusercontent.com/29533634/27304639-05d22846-553f-11e7-8e2f-d82d1af02f9e.png)

**Comment by vincenthure** [comment]
Done
