### ISSUE TITLE
Nouveau Projet Etape 3/5 - Informations

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#32]
Resevation studio > Réservation studio
Date de creation > Date de création
Mon 19/06/2017 22:27:00 > Lun 19/06/2017 22:27:00
![click mix - client_nouveau-projet-etape3](https://user-images.githubusercontent.com/29533634/27304765-6e091b4a-553f-11e7-894f-5c76480d3e4e.png)

**Comment by vincenthure** [comment]
done
