### ISSUE TITLE
Nouveau Projet Etape 3/5 - RESERVATIONS

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#33]
Reservation > Réservation
Le Friday 23/06/2017 à 15 heure > Le Vendredi 23/06/2017 à 15h00
![click mix - client_nouveau-projet-etape3_reservation](https://user-images.githubusercontent.com/29533634/27304851-bc8e959c-553f-11e7-88f3-8f9d4abc80d3.png)

**Comment by vincenthure** [comment]
Done
