### ISSUE TITLE
Nouveau Projet Etape 5/5 - Video Quicktime

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#35]
Quicktime n'existe plus il faut changer le wording ...
Quels formats sont acceptés ? .mp4 .mov .avi .mkv ...
![click mix - client_nouveau-projet-etape5-upload video](https://user-images.githubusercontent.com/29533634/27305422-df5f83b8-5541-11e7-9459-241f6263aa1f.png)

**Comment by vincenthure** [comment]
done
