### ISSUE TITLE
Nouveau Projet Etape 5/5 - Désactiver boutons suivant / retour

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#36]
Désactiver les boutons suivant / retour pendant l'Upload
![click mix - client_nouveau-projet-etape5-upload video](https://user-images.githubusercontent.com/29533634/27305607-90e3246e-5542-11e7-9887-716c8c8ce016.png)

**Comment by vincenthure** [comment]
Done
