### ISSUE TITLE
ESPACE CLIENT - Parcours 1er projet

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#37]
Passer par l'espace client (uniquement nouveau projet disponible) lors de la création du premier projet (register)
L'utilisateur est placé dans le contexte et comprend mieux le fonctionnement du site
![click mix - client_espace](https://user-images.githubusercontent.com/29533634/27305751-3ee3f228-5543-11e7-9feb-44548fc88165.png)

**Comment by vincenthure** [comment]
Done
