### ISSUE TITLE
Typo Nom Utilisateur

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#39]
Typo du nom utilisateur dans le Header différent du reste du site
![click mix - client_espace](https://user-images.githubusercontent.com/29533634/27306103-a3090468-5544-11e7-808e-5f627cc3f211.png)

**Comment by vincenthure** [comment]
done

**Comment by Lorisbar** [comment]
Non pas chez moi même après suppression du cache
