### ISSUE TITLE
Home - Connexion utilisateur

### ISSUE THREAD

**Issue by Lorisbar** [vincenthure/postmedias-beta#40]
Utilisateur est déconnecté chaque qu'il retourne sur la home
![click mix - home](https://user-images.githubusercontent.com/29533634/27306132-cde7018a-5544-11e7-90b5-0a33793659b0.png)

**Comment by vincenthure** [comment]
Attention  si ta page est en cache dans le navigateur il faut la recharger!!!
peux faire le test et me dire si ça résout le problème.

**Comment by vincenthure** [comment]
done
